services:

  backend:
    build: ./backend
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"     
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

volumes:
  dynamodb-data:
